### ISSUE TITLE
How to store 'Chunks' or Collection of String field?

### ISSUE THREAD

**Issue by miggytrinidad** [Azure-Samples/azure-search-power-skills#117]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Upload vector for a Collection of String(represented document chunking)

### Any log messages given by the failure
>
HttpResponseError: () The request is invalid. Details: An unexpected 'StartArray' node was found when reading from the JSON reader. A 'PrimitiveValue' node was expected.
Code: 
Message: The request is invalid. Details: An unexpected 'StartArray' node was found when reading from the JSON reader. A 'PrimitiveValue' node was expected.
### Expected/desired behavior
>

### Mention any other details that might be useful

How can we embed and store the vector for a collection of string field? The use case I am trying to do is, I am 'chunking' a document per ~1000 tokens to manage the token limits for OpenAI. 

I was able to vector the filename which works great! But the chunked collection of text is not working.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by arv100kri** [comment]
This powerskill only supports generating vector embeddings for a string field - not a collection of strings.
You could modify your skillset to select each chunk (documentation: https://learn.microsoft.com/azure/search/cognitive-search-skill-annotation-language) and then pass that to the powerskill for getting embeddings.

**Comment by arv100kri** [comment]
@bleroy - I think we should close out this bug as "by design"? @miggytrinidad let us know if the guidance makes sense?

**Comment by miggytrinidad** [comment]
This works thank you! How do you increase the timeout error for the vector custom skillset here? I am getting timeout whenever I try to use the function.
