### ISSUE TITLE
Issues with Sample JSON 

### ISSUE THREAD

**Issue by angusforeman** [Azure-Samples/azure-search-power-skills#122]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
The Sample JSON for "chunk-embed" in https://github.com/Azure-Samples/azure-search-power-skills/blob/main/Vector/EmbeddingGenerator/README.md will fail when used with the function python code due to the lack of double quotes around the recordId node e.g. ("recordId": 1234 should be "recordId": "1234")

Causes the Azure Function to fail to parse when sent with Postman

>

Azure function fails with error messages re malformed body when Az Function  accessed via Postman
>

Azure function succeeds when Az Function  accessed via Postman and returns embeddings
>

### OS and Version?
> Win 10, VS.Code used to deploy function. Postman

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by bleroy** [comment]
Thanks, fixed it.
