### ISSUE TITLE
Web Api response contains data properties for a record with invalid id

### ISSUE THREAD

**Issue by Alexon2018** [Azure-Samples/azure-search-power-skills#155]
error
--------
Enrichment.WebApiSkill.#1
Could not execute skill because Web Api skill response is invalid.
Web Api response contains data properties for a record with invalid id 'r1'

from Skillset
--------
...
{
      "@odata.type": "#Microsoft.Skills.Custom.WebApiSkill",
      "name": "#1",
      "description": "",
      "context": "/document",
      "uri": "https://f10-function.azurewebsites.net/api/f10_http_trigger?code=[REDACTED]",
      "httpMethod": "POST",
      "timeout": "PT30S",
      "batchSize": 1,
      "degreeOfParallelism": 1,
      "inputs": [
        {
          "name": "Categoria",
          "source": "/document/Categoria"
        }
      ],
      "outputs": [
        {
          "name": "comes_from_Skillset",
          "targetName": "comes_from_Skillset"
        }
      ],
      "httpHeaders": {}
    }
...

from Indexer
--------
...
  "outputFieldMappings": [
    {
      "sourceFieldName": "/document/comes_from_Skillset",
      "targetFieldName": "URL"
    }
  ],
...
//////////////////
Hello,

It looks like my python function/ Custom.WebApiSkill returns an invalid id.
Is there any python "hello world" function to start from, for this use-case?
How can this case be troubleshoot?

Ty

**Comment by bleroy** [comment]
Your report got flagged by GitHub as possibly containing a secret, that I redacted, but you should still revoke that secret if it was one.
As for troubleshooting, you can do that with s debug session.
