### ISSUE TITLE
In Azure search indexer after creating custom i got this errror while (check indexer status): SkillCould not execute skill. WebApi skill response contains errors.

### ISSUE THREAD

**Issue by rajat28negi** [Azure-Samples/azure-search-power-skills#19]
errors": [
            {
                "key": "https://*****.core.windows.net/container1/Azure%20Search%20Pricing%20Table.xlsx",
                "statusCode": 400,
                "name": "Enrichment.WebApiSkill.technology",
                "errorMessage": "Could not execute skill. WebApi skill response contains errors.",
                "details": "WebApi response contains both data and errors. Will not process Data.;**Cannot process record without the given key 'text' with a string value**",
                "documentationLink": "https://go.microsoft.com/fwlink/?linkid=2100103"
            }

**Index Field as Follows:**
"fields": [	
        {
            "name": "id",
            "type": "Edm.String",
            "searchable": true,
            "filterable": true,
            "retrievable": true,
            "sortable": true,
            "facetable": false,
            "key": true,
            "indexAnalyzer": null,
            "searchAnalyzer": null,
            "analyzer": null,
            "synonymMaps": []
        },        
        	{
	"name": "technology",
	"type": "Collection(Edm.String)",
	"searchable": true,
	"filterable": true,
	"retrievable": true,
	"sortable": false,
	"facetable": true,
	"key": false,
	"indexAnalyzer": null,
	"searchAnalyzer": null,
	"analyzer": "en.microsoft",
	"synonymMaps": []
   }
    ],

**Skillset is As Follows**
"skills":
  [ 	
    
    {
      "@odata.type": "#Microsoft.Skills.Text.SplitSkill",
      "textSplitMode": "pages",
      "maximumPageLength": 4000,
      "defaultLanguageCode": "en",
      "context": "/document",
      "inputs": [
        {
          "name": "text",
          "source": "/document/merged_text"
        }
      ],
      "outputs": [
        {
          "name": "textItems",
          "targetName": "pages"
        }
      ]
    },
    {
            "@odata.type": "#Microsoft.Skills.Custom.WebApiSkill",
            "name": "technology",
            "description": "Technology Extraction Skill",
            "context": "/document",
            "uri": "https://******-azuresearch.azurewebsites.net/api/*************************************************",
            "httpMethod": "POST",
            "timeout": "PT90S",
            "batchSize": 1,
            "inputs": [
                {
                    "name": "text",
                    "source": "/document/merged_content",
                    "inputs": []
                }
            ],
            "outputs": [
                {
                    "name": "technology",
                    "targetName": "technology"
                }
            ]
        }

  ]

Indexer Field mapping is as follows:
"fieldMappings": [
        {
            "sourceFieldName": "metadata_storage_path",
            "targetFieldName": "id",
            "mappingFunction": {
                "name": "base64Encode",
                "parameters": null
            }
        }
    ],
    "outputFieldMappings": [
      
        {
            "sourceFieldName": "/document/technology",
            "targetFieldName": "technology",
            "mappingFunction": null
        }
    ]

**Comment by bleroy** [comment]
Hi. This looks like the input mapping for the skill is not quite right. Can you share the skill definition from your skillset?

**Comment by rajat28negi** [comment]
> Hi. This looks like the input mapping for the skill is not quite right. Can you share the skill definition from your skillset?

hey @bleroy  i have updated the question . Please go through that

**Comment by bleroy** [comment]
Thanks, this will be helpful, but still missing one key piece of information: what power skill is behind this endpoint?

**Comment by rajat28negi** [comment]
@bleroy I go through this this function [](https://github.com/Azure-Samples/azure-search-power-skills/blob/master/Text/CustomEntitySearch/CustomEntityLookup.cs) and published it in azure ,
I have changed the dictionary data(word.csv) with my own data.

**Comment by bleroy** [comment]
It looks like some of your documents come up with an empty `/document/merged_content`. You could probably make sure by [using an `enriched` index field](https://docs.microsoft.com/en-us/azure/search/cognitive-search-concept-troubleshooting). One way to work around this would be to [modify the skill](https://github.com/Azure-Samples/azure-search-power-skills/blob/master/Text/CustomEntitySearch/CustomEntityLookup.cs#L63-67) so it doesn't error when text can't be found in the payload and returns an empty result instead.

**Comment by rajat28negi** [comment]
i am getting data in merged_content field of index.
and i also get the proper response through published azure function through postman.

**Comment by bleroy** [comment]
For that document in particular? I don't know what more to tell you: [the only place in the code where this error can be generated is in `CustomEntityLookup.cs`](https://github.com/Azure-Samples/azure-search-power-skills/blob/master/Text/CustomEntitySearch/CustomEntityLookup.cs#L63-L67) and that just checks the presence of a non-null parameter on the input data named "Text". Your skill inputs map `/document/merged_content` to `Text` so unless I'm missing something the only possibilities are that the code you're running is different from what's in this repo, or `merged-content` is null for that document, or the information above is somehow inaccurate. I'm sorry, I'm not sure what to try next.

**Comment by rajat28negi** [comment]
Thanks @bleroy there was mapping error as well as the merged_content of document was null.
May i get to know how these field(merged_content, content) for the particular doc generated?

**Comment by bleroy** [comment]
Glad you found what the problem was! The details depend on the data source you're using, but essentially, and if I remember correctly, content is typically created by the data source, and merged_content is where skills such as the entity detection skill output their results with the sort of default configuration the portal can generate for you when you create an indexer. Since your skillset seems to be very lean in comparison, my guess would be that no skill actually outputs anything to merged_content and that's why it was null.

**Comment by bleroy** [comment]
(I'll close this tomorrow unless you object before then; thanks for your patience)
