### ISSUE TITLE
Custom Entity Serarch - Deploy to Azure not working

### ISSUE THREAD

**Issue by oex-pbi** [Azure-Samples/azure-search-power-skills#38]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
From link: https://github.com/Azure-Samples/azure-search-power-skills/tree/master/Text/CustomEntitySearch

Deploy to Azure button feature doesnt work correctly

### Any log messages given by the failure
>
![image](https://user-images.githubusercontent.com/54525999/92215935-73dec480-ee8d-11ea-8b54-98854b821b82.png)

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10, Chrome
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by bleroy** [comment]
Good catch, thanks. Fixed it.
