### ISSUE TITLE
Can we get an option to process multiple images in a single page?

### ISSUE THREAD

**Issue by ppdalua** [Azure-Samples/azure-search-power-skills#39]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ppdalua** [comment]
Currently the functionality involves identifying one image per page. I wish if there can be a way to figure out multiple images per page

**Comment by bleroy** [comment]
What skill are you referring to?
