### ISSUE TITLE
Image Clustering: Cleanup comments

### ISSUE THREAD

**Issue by shanepeckham** [Azure-Samples/azure-search-power-skills#57]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by bleroy** [comment]
Can you provide any information about what the issue is?

**Comment by shanepeckham** [comment]
I wanted to track an issue against the open PR (https://github.com/Azure-Samples/azure-search-power-skills/pull/58). The issue is that there were a few comments that needed to be removed, in case they caused confusion in the image clustering skill.
