### ISSUE TITLE
Text Summarisation PowerSkill is missing the Dockerfile

### ISSUE THREAD

**Issue by ross-p-smith** [Azure-Samples/azure-search-power-skills#68]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> The Readme file [https://github.com/Azure-Samples/azure-search-power-skills/blob/main/Text/TextSummarization/README.md
](https://github.com/Azure-Samples/azure-search-power-skills/blob/main/Text/TextSummarization/README.md
) talks about building a dockerfile and pushing it to your ACR. There is no Dockerfile in teh repo and the link to it 404s https://github.com/Azure-Samples/azure-search-power-skills/blob/main/Text/TextSummarization/Dockerfile 
### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by bleroy** [comment]
It's there, just under powerskill. I fixed the link.
