### ISSUE TITLE
Deploy failed

### ISSUE THREAD

**Issue by qawnaoya** [Azure-Samples/azure-search-power-skills#70]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Deploy to some resource
[デプロイ-Microsoft.Template-20210701160805.zip](https://github.com/Azure-Samples/azure-search-power-skills/files/6746144/-Microsoft.Template-20210701160805.zip)

### Any log messages given by the failure
Conflict on deploy

### Expected/desired behavior
Deploy was suceed

### OS and Version?
Windows 10

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by bleroy** [comment]
Hi. It looks like one of the resources you're trying to deploy already exists, apparently "pscv02-function-app-6aeswd35yhf2a/web". You can either modify your deployment file to target a resource with a different name, or remove that resource before deploying if that's your intent.

**Comment by qawnaoya** [comment]
There is no resource named pscv02-function-app-6aeswd35yhf2a.

**Comment by bleroy** [comment]
Then I don't know what's going wrong, you'd probably get better insights from the Azure Functions team. You could also try to deploy the function manually from Visual Studio or on the portal.
