### ISSUE TITLE
Executio failed

### ISSUE THREAD

**Issue by qawnaoya** [Azure-Samples/azure-search-power-skills#73]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [O] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Reset indexer ＆ Execute

### Any log messages given by the failure
>このセッションは、次のエラーから作成されました:
操作: Enrichment.WebApiSkill.#8
メッセージ: Could not execute skill because Web Api skill response is invalid.
詳細: Web Api skill response contains errors: 'Web Api response contains both data and errors. Will not process Data.;custom-vision - Error processing the request record : System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at CustomVision.CustomVision.<>c__DisplayClass4_0.<<RunCustomVision>b__0>d.MoveNext() in C:\Users\nikeda\Projects\QAW\DS\Azure\azure-search-power-skills\Vision\CustomVision\CustomVision.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at AzureCognitiveSearch.PowerSkills.Common.WebApiSkillHelpers.ProcessRequestRecordsAsync(String functionName, IEnumerable`1 requestRecords, Func`3 processRecord) in C:\Users\nikeda\Projects\QAW\DS\Azure\azure-search-power-skills\Common\WebAPISkillHelper.cs:line 67'.
ドキュメント キー: localId=https%3a%2f%2fkmdocstore.blob.core.windows.net%2fdocuments%2f01_%25E6%2595%2599%25E8%2582%25B2%25E9%2596%25A2%25E9%2580%25A3%2f00_DX%25E9%2596%25A2%25E9%2580%25A3%2f%25E3%2580%2590%25E9%2585%258D%25E5%25B8%2583%25E7%2594%25A8%25E3%2580%2591DX%25E3%2581%25AE%25E6%259C%2580%25E6%2596%25B0%25E5%258B%2595%25E5%2590%2591%25E3%2581%25A8%25E3%2583%2587%25E3%2582%25B8%25E3%2582%25BF%25E3%2583%25AB%25E4%25BA%25BA%25E6%259D%2590%25E8%2582%25B2%25E6%2588%2590%25E3%2581%25AE%25E3%2583%259D%25E3%2582%25A4%25E3%2583%25B3%25E3%2583%2588ver1.031.pptx&documentKey=https%3a%2f%2fkmdocstore.blob.core.windows.net%2fdocuments%2f01_%25E6%2595%2599%25E8%2582%25B2%25E9%2596%25A2%25E9%2580%25A3%2f00_DX%25E9%2596%25A2%25E9%2580%25A3%2f%25E3%2580%2590%25E9%2585%258D%25E5%25B8%2583%25E7%2594%25A8%25E3%2580%2591DX%25E3%2581%25AE%25E6%259C%2580%25E6%2596%25B0%25E5%258B%2595%25E5%2590%2591%25E3%2581%25A8%25E3%2583%2587%25E3%2582%25B8%25E3%2582%25BF%25E3%2583%25AB%25E4%25BA%25BA%25E6%259D%2590%25E8%2582%25B2%25E6%2588%2590%25E3%2581%25AE%25E3%2583%259D%25E3%2582%25A4%25E3%2583%25B3%25E3%2583%2588ver1.031.pptx

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gmndrg** [comment]
Not enough information to repro. If anyone has a similar error, please raise a support ticket in the Azure portal for assistance.
